+
Searge/filmoteka pull request #160
Opened 2021-12-16 22:20 UTC by Serhii-P79

хедер, фон, модалка, пагинация - стили для темной темы

2021-12-16 22:29 UTC, Searge requested changes
Не переписуй чужий код, створи окремий для теми і додай класом, який переписуватиме значення.

2021-12-16 22:29 UTC, Searge commented on src/js/modal.js
> -  // console.log(event.target.dataset);
Навіщо цей код?

2021-12-16 22:29 UTC, Searge commented on src/sass/layout/_header.scss
> +  background-color: #444;
Зроби для кольорів темної теми окремі змінні, а краще: variables_themename.scss

2021-12-17 01:05 UTC, OlgaOnoshko approved these changes

2021-12-17 08:29 UTC, closed without merging